language: node_js
node_js:
  - "9.9.0"

branches:
  only:
    - develop

before_script:
  - npm install -g firebase-tools
  - npm install -g gulp-cli
  - npm install

script:
  - npm run build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    recipients:
      - scoletta.developer@gmail.com
    on_failure: change
    on_success: change
